const KoaRouter = require('koa-router')

const Book = require('../../models/book')
const helper = require('../helper')
const bookSchemas = require('../../common/validationSchemas/book')
const ERRORS = require('../../common/errors')

const router = new KoaRouter()

const booksCollectionName = 'books'

router.get('/:id', async ctx => {
    const _id = ctx.params.id //TODO: validate that id can be cast to ObjectId (id generated by mongo)

    const book = await Book.findOne({ _id })

    if (book === null) throw {
        name: ERRORS.NOT_FOUND,
        message: `No book with id ${_id}`
    }
    return ctx.body = book
})

router.get('/', async ctx => {
    let {perPage = 10, page = 1} = ctx.request.query
    const { sort = 'name', language, title } = ctx.request.query

    perPage = Number.parseInt(perPage)
    page = Number.parseInt(page) - 1 // Subtracting one because Mongo starts counting from 0

    //validation
    helper.mustValidate(perPage, bookSchemas.perPage)

    const query = {}
    if (language) query.language = language
    if (title) query.title = {"$regex": title, "$options": "i"} //Todo: title is user input, don't I need to sanitize it?

    const countPromise = Book
        .find(query)
        .count()
    const booksPromise = Book
        .find(query)
        .skip(perPage*page)
        .limit(perPage)
        .sort(sort)

    const [books, count] = await Promise.all([booksPromise, countPromise])

    return ctx.body = {
        books,
        page: ++page,
        perPage,
        count,
        hasNextPage: (count - page * perPage > 0)? true : false,
    }
})

router.post('/', async ctx => {

    //validating
    helper.mustValidate(ctx.request.body, bookSchemas.postBook)

    //TODO: add ownerId based on session once users are handled
    const newBook = new Book(Object.assign({status: 'pending', timesRead: 0, readBy: []}, ctx.request.body))

    const createdBook = await newBook.save()

    ctx.status = 201
    ctx.response.body = createdBook
})

//TODO: Put this route in place 
router.put('/:id', async ctx => {
    const _id = ctx.params.id

})

router.delete('/:id', async ctx => {
    const _id = ctx.params.id
    const { deletedCount } = await Book.deleteOne({ _id })

    if (deletedCount === 0) {
        ctx.status = 204
        return
    }

    ctx.status = 200
})

router.post('/defaultSeed', async ctx => {
    const defaultBooks = [
        {
            title: "Sherlock Holmes: The Complete Stories",
            author: "Sir Arthur Conan Doyle",
            language: "english",
            description: "A dazzling compendium featuring all four original Sherlock Holmes novels Perfect for mystery lovers, this anthology collects together the only four full-length novels starring the super sleuth Sherlock Holmes.",
            coverPath: "https://images.gr-assets.com/books/1417088970l/617375.jpg",
        },
        {
            title: "A Song Of Ice And Fire: A Feast Of Crows",
            author: "George R.R Martin",
            language: "english",
            description: "A Feast for Crows is the fourth of seven planned novels in the epic fantasy series A Song of Ice and Fire by American author George R. R. Martin.",
            coverPath: "https://images-na.ssl-images-amazon.com/images/I/71nJQs9rawL.jpg",
        },
        {
            title: "Margaret Thatcher: The Autobiography",
            author: "Margaret Thatcher",
            language: "english",
            description: "A newly edited, single-volume commemorative edition of 'The Path to Power' and 'The Downing Street Years'; this is Margaret Thatcher in her own words.",
            coverPath: "https://images-na.ssl-images-amazon.com/images/I/51nf32f38EL._SY344_BO1,204,203,200_.jpg",
        },
        {
            title: "Physics of the Future",
            author: "Michio Kaku",
            language: "english",
            description: "Physics of the Future: How Science Will Shape Human Destiny and Our Daily Lives by the Year 2100 is a 2011 book by theoretical physicist Michio Kaku, author of Hyperspace and Physics of the Impossible.",
            coverPath: "https://images-eu.ssl-images-amazon.com/images/I/51YwpRXgorL._SY291_BO1,204,203,200_QL40_.jpg",
        },
        {
            title: "Parce que je t'aime",
            author: "Guillaume Musso",
            language: "french",
            description: "Layla, une petite fille de cinq ans, disparaît dans un centre commercial de Los Angeles. Ses parents, brisés, finissent par se séparer. Cinq ans plus tard, elle est retrouvée à l'endroit exact où on avait perdu sa trace. Elle est vivante, mais reste plongée dans un étrange mutisme. À la joie des retrouvailles, succèdent alors les interrogations. Où était Layla pendant cette période? Avec qui ? Et surtout pourquoi est-elle revenue ?",
            coverPath: "http://www.guillaumemusso.com/wp-content/uploads/2014/03/9782845635395-625x1024.jpg",
        },
    ]

    await Book.db.dropCollection(booksCollectionName)

    defaultBooks.forEach(async book => {
        const newBook = new Book(Object.assign({status: 'pending', timesRead: 0, readBy: []}, book))
        await newBook.save()
    })

    ctx.status = 201
})

module.exports = router