const defaultBooks = [
    {
        title: "Sherlock Holmes: The Complete Stories",
        author: "Sir Arthur Conan Doyle",
        language: "english",
        description: "A dazzling compendium featuring all four original Sherlock Holmes novels Perfect for mystery lovers, this anthology collects together the only four full-length novels starring the super sleuth Sherlock Holmes.",
        coverPath: "https://images.gr-assets.com/books/1417088970l/617375.jpg",
        genres: ["mystery"],
        status: "ready",
    },
    {
        title: "Margaret Thatcher: The Autobiography",
        author: "Margaret Thatcher",
        language: "english",
        description: "A newly edited, single-volume commemorative edition of 'The Path to Power' and 'The Downing Street Years'; this is Margaret Thatcher in her own words.",
        coverPath: "https://images-na.ssl-images-amazon.com/images/I/51nf32f38EL._SY344_BO1,204,203,200_.jpg",
        genres: ["autobiography"],
        status: "ready",
    },
    {
        title: "Physics of the Future",
        author: "Michio Kaku",
        language: "english",
        description: "Physics of the Future: How Science Will Shape Human Destiny and Our Daily Lives by the Year 2100 is a 2011 book by theoretical physicist Michio Kaku, author of Hyperspace and Physics of the Impossible.",
        coverPath: "https://images-eu.ssl-images-amazon.com/images/I/51YwpRXgorL._SY291_BO1,204,203,200_QL40_.jpg",
        genres: ["science"],
        status: "ready",
    },
    {
        title: "Parce que je t'aime",
        author: "Guillaume Musso",
        language: "french",
        description: "Layla, une petite fille de cinq ans, disparaît dans un centre commercial de Los Angeles. Ses parents, brisés, finissent par se séparer. Cinq ans plus tard, elle est retrouvée à l'endroit exact où on avait perdu sa trace. Elle est vivante, mais reste plongée dans un étrange mutisme. À la joie des retrouvailles, succèdent alors les interrogations. Où était Layla pendant cette période? Avec qui ? Et surtout pourquoi est-elle revenue ?",
        coverPath: "http://www.guillaumemusso.com/wp-content/uploads/2014/03/9782845635395-625x1024.jpg",
        genres: ["drama"],
        status: "ready",
    },
    {
        title: "A Song Of Ice And Fire: A Game Of Thrones",
        author: "George R.R Martin",
        language: "english",
        description: "A Game of Thrones is the first novel in A Song of Ice and Fire, a series of fantasy novels by American author George R. R. Martin. It was first published on August 1, 1996.",
        coverPath: "http://georgerrmartin.com/gallery/coverart/GOThcEng.jpg",
        genres: ["fantasy"],
        status: "ready",
    },
    {
        title: "A Song Of Ice And Fire: A Clash of Kings",
        author: "George R.R Martin",
        language: "english",
        description: "A Clash of Kings is the second novel in A Song of Ice and Fire, an epic fantasy series by American author George R. R. Martin expected to consist of seven volumes.",
        coverPath: "https://images-na.ssl-images-amazon.com/images/I/51o2UG3sp3L._SX305_BO1,204,203,200_.jpg",
        genres: ["fantasy"],
        status: "ready",
    },
    {
        title: "A Song Of Ice And Fire: A Storm of Swords",
        author: "George R.R Martin",
        language: "english",
        description: "A Storm of Swords is the third of seven planned novels in A Song of Ice and Fire, a fantasy series by American author George R. R. Martin.",
        coverPath: "http://1.bp.blogspot.com/-tvOE1oNZsQU/UFC73H7PZ-I/AAAAAAAABpk/Y_J_GZ-3bcs/s1600/9780007447848.jpg",
        genres: ["fantasy"],
        status: "ready",
    },
    {
        title: "A Song Of Ice And Fire: A Feast Of Crows",
        author: "George R.R Martin",
        language: "english",
        description: "A Feast for Crows is the fourth of seven planned novels in the epic fantasy series A Song of Ice and Fire by American author George R. R. Martin.",
        coverPath: "https://images-na.ssl-images-amazon.com/images/I/71nJQs9rawL.jpg",
        genres: ["fantasy"],
        status: "ready",
    },
    {
        title: "A Song Of Ice And Fire: A Dance With Drangons",
        author: "George R.R Martin",
        language: "english",
        description: "A Dance with Dragons is the fifth of seven planned novels in the epic fantasy series A Song of Ice and Fire by American author George R. R. Martin.",
        coverPath: "http://t0.gstatic.com/images?q=tbn:ANd9GcRSd90gkm23TFj2nLudU3yQaHDDBYh3hV-Q4eUCmpUyZfcC2d_W",
        genres: ["fantasy"],
        status: "ready",
    },
    {
        title: "Harry Potter and the Philosopher's Stone",
        author: "J. K. Rowling",
        language: "english",
        description: "Harry Potter and the Philosopher's Stone is a fantasy novel written by British author J. K. Rowling. It is the first novel in the Harry Potter series and Rowling's debut novel, first published in 1997 by Bloomsbury.",
        coverPath: "https://static.independent.co.uk/s3fs-public/styles/article_small/public/thumbnails/image/2016/02/26/13/3-Harry-Potter-and-the-Philosophers-Stone.jpg",
        genres: ["fantasy"],
        status: "ready",
    },
    {
        title: "Harry Potter and the Chamber of Secrets",
        author: "J. K. Rowling",
        language: "english",
        description: "Harry Potter and the Chamber of Secrets is a fantasy novel written by British author J. K. Rowling and the second novel in the Harry Potter series.",
        coverPath: "https://images-na.ssl-images-amazon.com/images/I/51jNORv6nQL.jpg",
        genres: ["fantasy"],
        status: "ready",
    },
    {
        title: "Harry Potter and the Prisoner of Azkaban",
        author: "J. K. Rowling",
        language: "english",
        description: "Harry Potter and the Prisoner of Azkaban is a fantasy novel written by British author J. K. Rowling and the third novel in the Harry Potter series.",
        coverPath: "http://images.contentful.com/7h71s48744nc/afIHQyAZxh8CxK3SE2URv2/039fb0d022c214b300ad63e07c1b3996/harry-potter-and-the-prisoner-of-azkaban-cover-image",
        genres: ["fantasy"],
        status: "ready",
    },
    {
        title: "Harry Potter and the Goblet of Fire",
        author: "J. K. Rowling",
        language: "english",
        description: "Harry Potter and the Goblet of Fire is a fantasy book written by British author J. K. Rowling and the fourth novel in the Harry Potter series.",
        coverPath: "https://images-na.ssl-images-amazon.com/images/I/41AF6KHRGML.jpg",
        genres: ["fantasy"],
        status: "ready",
    },
    {
        title: "Harry Potter and the Order of the Phoenix",
        author: "J. K. Rowling",
        language: "english",
        description: "Harry Potter and the Order of the Phoenix is a fantasy novel written by J. K. Rowling and the fifth novel in the Harry Potter series.",
        coverPath: "https://upload.wikimedia.org/wikipedia/en/7/70/Harry_Potter_and_the_Order_of_the_Phoenix.jpg",
        genres: ["fantasy"],
        status: "ready",
    },
    {
        title: "Harry Potter and the Deathly Hallows",
        author: "J. K. Rowling",
        language: "english",
        description: "Harry Potter and the Deathly Hallows is a fantasy novel written by British author J. K. Rowling and the seventh and final novel of the Harry Potter series.",
        coverPath: "https://vignette.wikia.nocookie.net/harrypotter/images/1/15/Hp7.jpg/revision/latest/scale-to-width-down/180?cb=20070927074347",
        genres: ["fantasy"],
        status: "ready",
    },
]

module.exports = defaultBooks